# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.1.0" # v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=500000]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: "v1.1.13" # v1.1.10
    hooks:
      - id: remove-crlf
      - id: remove-tabs
  - repo: https://github.com/sirosen/fix-smartquotes
    rev: "0.2.0" # 0.2.0
    hooks:
      - id: fix-smartquotes
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.5.1" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "v0.31.1" # v0.30.0
    hooks:
      - id: markdownlint
        args: ["-f"]
  # - repo: https://github.com/adrienverge/yamllint.git
  #   rev: v1.26.3
  #   hooks:
  #     - id: yamllint
  #       args: [-c=.yamllint.yaml]
  # - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  #   rev: 0.1.0
  #   hooks:
  #     - id: yamlfmt
  #       args: [--mapping, '2', --sequence, '4', --offset, '2', --preserve-quotes]
  - repo: https://github.com/pycqa/isort
    rev: "5.10.1" # 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: "22.1.0" # 21.11b1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1" # 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-builtins
          - flake8-colors
          - flake8-comprehensions
          - flake8-isort
          - pep8-naming
