---
- hosts: localhost

  vars_files:
    - config.yaml
    - vars/homebrew_vars.yaml
    - vars/dock_vars.yaml
    - vars/terminal_vars.yaml

  roles:
    - role: elliotweiser.osx-command-line-tools

    - role: geerlingguy.mac.homebrew
      # override defaults & set homebrew dirs to manage
      homebrew_folders_base:
        - Cellar
        - Homebrew
        - Frameworks
        - Caskroom
        - bin
        - etc
        - include
        - lib
        - opt
        - sbin
        - share
        - share/info
        - share/man
        - share/man/man3
        - share/man/man5
        - share/zsh
        - share/zsh/site-functions
        - var
      when: configure_homebrew
      tags: ['env', 'homebrew']

    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/conda.yaml
      when: configure_conda
      tags: ['env', 'conda']

    - import_tasks: tasks/terminals.yaml
      when: configure_terminals
      tags: ['env', 'terminals']

    - import_tasks: tasks/zsh.yaml
      when: configure_zsh
      tags: ['env', 'zsh']

    - import_tasks: tasks/macos.yaml
      when: configure_macos
      tags: ['macos']
