---
- hosts: localhost

  vars_files:
    - vars/dock_vars.yaml
    - vars/homebrew_vars.yaml
    - vars/vscode_env.yaml

  tasks:
    - name: install homebrew
      include_role:
        name: geerlingguy.mac.homebrew

    - name: fix dock
      include_role:
        name: geerlingguy.mac.dock

    - name: conda setup
      include_role:
        name: conda

    - name: vscode setup
      include_role:
        name: vscode

    - name: zsh setup
      include_role:
        name: zsh
