---
- hosts: localhost

  vars_files:
    - config.yaml
    - vars/homebrew_vars.yaml
    - vars/dock_vars.yaml
    - vars/terminal_vars.yaml

  roles:
    - role: elliotweiser.osx-command-line-tools

    - role: geerlingguy.mac.homebrew
      ### override defaults & set homebrew dirs to manage
      homebrew_prefix: "/opt/homebrew"
      # homebrew_installed_packages: []  # uncommenting will to skip installing packages
      # homebrew_cask_apps: []           # uncommenting will to skip installing apps
      when: configure_homebrew
      tags: ["env", "homebrew"]

    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ["dock"]

  tasks:
    - import_tasks: tasks/conda.yaml
      when: configure_conda
      tags: ["env", "conda"]

    - import_tasks: tasks/terminals.yaml
      when: configure_terminals
      tags: ["env", "terminals"]
