---
- hosts: localhost

  vars_files:
    - config.yaml
    - vars/homebrew_vars.yaml
    - vars/dock_vars.yaml
    - vars/terminal_vars.yaml

  roles:
    - role: elliotweiser.osx-command-line-tools

    - role: geerlingguy.mac.homebrew
      when: configure_homebrew
      tags: ['env', 'homebrew']

    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/conda.yaml
      when: configure_conda
      tags: ['env', 'conda']

    - import_tasks: tasks/terminals.yaml
      when: configure_terminals
      tags: ['env', 'conda']

    - import_tasks: tasks/zsh.yaml
      when: configure_zsh
      tags: ['env', 'zsh']

    - import_tasks: tasks/macos.yaml
      when: configure_macos
      tags: ['macos']
