---
- hosts: localhost

  vars_files:
    - vars/dock_vars.yaml
    - vars/homebrew_vars.yaml
    - vars/vscode_env.yaml

  tasks:
    - name: install Rosetta
      shell: |
        # install x86 compatibility layer
        if [[ "$(arch)" = "arm64" ]]; then
          softwareupdate --install-rosetta --agree-to-license
        fi

    - name: install homebrew
      include_role:
        name: geerlingguy.homebrew

    - name: fix dock
      include_role:
        name: geerlingguy.dock

    - name: conda setup
      include_role:
        name: conda

    - name: vscode setup
      include_role:
        name: vscode

    - name: zsh setup
      include_role:
        name: zsh
