---
- name: 'Check if conda (mambaforge) installed'
  shell: |
    [[ -f $HOME/mambaforge/bin/conda ]]
  args:
    executable: /bin/bash
  register: conda_exists
  ignore_errors: yes

- name: 'Install conda (mambaforge'
  shell: |
    curl -L -O https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh
    bash Mambaforge-$(uname)-$(uname -m).sh -b -f -p $HOME/mambaforge
    rm Mambaforge-$(uname)-$(uname -m).sh
  args:
    executable: /bin/bash
  when: conda_exists.rc != 0

# get/test current working directory
- shell: pwd
  register: shell_pwd
  when: debug
- debug: var=shell_pwd.stdout
  when: debug

# - name: 'Conda init'
#   shell: |
#     "$HOME/mambaforge/bin/conda" init zsh
#   args:
#     executable: /bin/zsh

# - name: 'Check if default env exists'
#   shell: |
#     [[ -d $HOME/mambaforge/envs/default ]]
#   args:
#     executable: /bin/bash
#   register: default_env_exists
#   ignore_errors: yes

# - name: 'Install Default Python'
#   shell: |
#     # conda() { "$HOME/mambaforge/bin/conda"; }
#     # mamba() { "$HOME/mambaforge/bin/mamba"; }
#     export PATH="$HOME/mambaforge/bin":$PATH

#     conda create --name default -yq
#     conda activate default
#     mamba env -n default update --file ./files/conda/environment.yaml \
#       && pip install -r ./files/conda/requirements.txt
#     conda deactivate
#   args:
#     executable: /bin/zsh
#   when: default_env_exists.rc != 0
