---
- shell: pwd
  register: shell_pwd
  when: debug

- debug: var=shell_pwd.stdout
  when: debug

- name: Run macos configuration
  script: 'scripts/macos_settings.sh --no-restart'
  args:
    executable: /bin/bash
  become: true
