---
- shell: pwd
  register: shell_pwd
  when: debug

- debug: var=shell_pwd.stdout
  when: debug

- name: Copy VSCode configuration
  copy:
    src: ../files/vscode/settings.json
    dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/Code/User/settings.json
    owner: "{{ lookup('env', 'USER') }}"
    force: no

- name: Copy VSCode keybinding
  copy:
    src: ../files/vscode/vscode-keybindings.json
    dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/Code/User/keybindings.json
    owner: "{{ lookup('env', 'USER') }}"
    force: no

- name: Install VSCode extensions
  shell: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"

- name: Copy iTerm profile
  copy:
    src: ../files/iterm/Dynamic.json
    dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/iTerm2/DynamicProfiles/Profiles.json
    owner: "{{ lookup('env', 'USER') }}"
    force: no

# Custom Terminal theme.
- name: Get current Terminal profile.
  command: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false
  check_mode: false

- name: Ensure custom Terminal profile is added.
  command: open ../files/terminal/MaterialDarker.terminal
  changed_when: false
  when: "'MaterialDarker' not in terminal_theme.stdout"

# TODO: This doesn't work in Yosemite. Consider a different solution?
- name: Ensure custom Terminal profile is set as default.
  command: "{{ item }}"
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' -string MaterialDarker
    - defaults write com.apple.terminal 'Startup Window Settings' -string MaterialDarker
  changed_when: false
  when: "'MaterialDarker' not in terminal_theme.stdout"
