---
- shell: pwd
  register: shell_pwd
  when: debug

- debug: var=shell_pwd.stdout
  when: debug

- name: Ensure VSCode User directory exists.
  file:
    path: "/Users/{{ lookup('env', 'USER') }}/Library/Application Support/Code/User"
    owner: "{{ lookup('env', 'USER') }}"
    # group: "{{ homebrew_group }}"
    state: directory
    mode: 0755
  become: true

- name: Copy VSCode configuration
  copy:
    src: files/vscode/settings.json
    dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/Code/User/settings.json
    owner: "{{ lookup('env', 'USER') }}"
    force: no

- name: Copy VSCode keybinding
  copy:
    src: files/vscode/keybindings.json
    dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/Code/User/keybindings.json
    owner: "{{ lookup('env', 'USER') }}"
    force: no

- name: Install VSCode extensions
  shell: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"

- name: Ensure iTerm dynamicprofiles directory exists.
  file:
    path: "/Users/{{ lookup('env', 'USER') }}/Library/Application Support/iTerm2/DynamicProfiles"
    owner: "{{ lookup('env', 'USER') }}"
    # group: "{{ homebrew_group }}"
    state: directory
    mode: 0755
  become: true

- name: Copy iTerm profile
  copy:
    src: files/iterm/Dynamic.json
    dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/iTerm2/DynamicProfiles/Profiles.json
    owner: "{{ lookup('env', 'USER') }}"
    force: no

# Custom Terminal theme.
- name: Get current Terminal profile.
  command: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false
  check_mode: false

- name: Ensure custom Terminal profile is added.
  command: open files/terminal/MaterialDarker.terminal
  changed_when: false
  when: "'MaterialDarker' not in terminal_theme.stdout"

- name: Ensure custom Terminal profile is set as default.
  command: "{{ item }}"
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' -string MaterialDarker
    - defaults write com.apple.terminal 'Startup Window Settings' -string MaterialDarker
  changed_when: false
  when: "'MaterialDarker' not in terminal_theme.stdout"

# only if running from remote
# - name: Check if Terminal is Active.
#   shell: ps aux | grep -F 'Terminal' | grep -v -F 'grep' | awk '{ print $2 }'
#   register: terminal_pid
#   changed_when: false

# - name: Restart Terminal if it's running to activate the new profile.
#   shell: |
#     osascript -e 'quit app "Terminal"'
#     open -a Terminal
#   changed_when: false
#   when: terminal_pid.stdout != ""
